### ISSUE TITLE
tikv client error

### ISSUE THREAD

**Issue by mehdipourfar** [tidb-incubator/tidis#109]
Hi. I'm running `tikv` with the following command:
```sh
tiup playground v8.0.0 --mode tikv-slim
```

my `tidis` is clone of master branch and I've build it with the command `make release`

I'm running `tidis` with the config bellow:

```toml
[server]
listen = "0.0.0.0"
port = 6380                               # disable tcp port if set to 0
tls_listen = "0.0.0.0"
tls_port = 0                            # disable tls if tls_port set to 0
tls_key_file = ""                         # disable tls if key or cert file not set
tls_cert_file = ""
tls_auth_client = false                   # tls_ca_cert_file must be specified if tls_auth_client is true
pd_addrs = "127.0.0.1:2379"               # PD addresses of the TiKV cluster
instance_id = "1"                         # instance_id can be used as tenant identifier
# prometheus_listen = "0.0.0.0"
# prometheus_port = 8080
log_level = "info"
log_file = "tidis.log"

[backend]
use_txn_api = true                        # use transaction api for full api supported
use_async_commit = true                   # try to use async commit in tikv
try_one_pc_commit = true                  # try to use one pc commit
use_pessimistic_txn = true                # use optimistic transaction mode
local_pool_number = 4                     # localset pool number for handle connections
txn_retry_count = 10                      # transaction retry count
txn_region_backoff_delay_ms = 2           # transaction region error backoff base delay time
txn_region_backoff_delay_attemps = 2      # transaction region error backoff retry max attempts
txn_lock_backoff_delay_ms = 2             # transaction lock error backoff base delay time
txn_lock_backoff_delay_attemps = 5        # transaction lock error backoff retry max attempts
```

However, when I connect to `tidis` with redis-cli and I run some simple commands I get the following error:
```
2024/03/22 04:17:29.977 +03:30 ERRO error occured so rollback transaction: PessimisticLock error: MultipleKeyErrors([KeyError(KeyError { locked: None, retryable: "", abort: "Error(ApiVersionNotMatched { cmd: prewrite, storage_api_version: V1ttl, req_api_version: V1 })", conflict: None, already_exist: None, deadlock: None, commit_ts_expired: None, txn_not_found: None, commit_ts_too_large: None, assertion_failed: None })])
```
